close_removed support
hetznerZA/hetzner-filebeats pull request #9
Opened 2018-03-19 11:44 UTC by belskiiartem

Thanks again for the great module, and check please my pull request.
It will add possibilities for adding **close_removed** parameters to configuration, because with current configuration filebeat lock files, and it can fill up filesystem.

2018-03-19 12:22 UTC, shaunbugler commented
Thanks for the contribution, I'll have a look at it this week!

2018-04-16 07:02 UTC, belskiiartem commented
Hi, @shaunbugler !
Probably you can find some time, and check my pull request?

Thank you in advance,
Artem

2018-04-23 12:00 UTC, shaunbugler requested changes
please check the filebeat.yml.erb, I believe the close_rmoved_for_all needs to move below the prospector loop

2018-04-23 12:00 UTC, shaunbugler commented on templates/filebeat.yml.erb
> +<% if @close_removed_for_all -%>
Shouldn't this be move below the prospector loop, just above the registry_file entry, otherwise it will be included in the prospector loop

2018-09-19 12:10 UTC, closed without merging